WIP fix(redimg): suppress exception if sub not found
Telegram-Bot-Node/Nikoro pull request #171
Opened 2020-09-01 09:08 UTC by blackdev1l

2020-09-01 14:51 UTC, CapacitorSet requested changes
La PR è ok. Dai un occhio ai commenti che ti ho lasciato, fai girare il linter (ci sono un po' di trailing space) e poi si può mergiare

2020-09-01 14:51 UTC, CapacitorSet commented on src/plugins/Reddit.js
> -    static reddit(message, results) {
Perchè non è più static?

2020-09-01 14:51 UTC, CapacitorSet commented on src/plugins/Reddit.js
> +    async sendRequest(url) {
Perchè serve questa funzione?

2020-09-02 15:38 UTC, blackdev1l commented on src/plugins/Reddit.js
> +    async sendRequest(url) {
ho encapsulato la funzione di invio della request per poter fare chaining e gestire l'eccezione con catch()

2020-09-02 15:39 UTC, blackdev1l commented on src/plugins/Reddit.js
> -    static reddit(message, results) {
pensavo foss inutile avere una funzione static utilizzata solo all'interno di questa classe

2020-09-02 17:11 UTC, merged